version: '3.1'

services:
  mysql:
    build: esmaelgoncalves/mysql-5.7.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: controlefinanceiro

  controle-financeiro-api:
    build: esmaelgoncalves/controlefinanceiroapi
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080