FROM mysql:5.7.25

MAINTAINER Esmael Gonçalves Pains <esmael.goncalves@hotmail.com>

#ENV MYSQL_USER=root \
#    MYSQL_DATABASE=controlefinanceiro \
#    MYSQL_ROOT_PASSWORD=password

ADD ./scripts/V001__create_database.sql /docker-entrypoint-initdb.d